[package]
name = "text_vectorize"
version = "0.1.0"
authors = ["Roman Yurchak <rth.yurchak@pm.me>"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false

[dependencies]
regex = "1"
lazy_static = "1.2.0"
fnv = "1.0.3"
fasthash = "0.3"
sprs = "0.6.2"
